version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo-app
      DB_HOST: db
    networks:
      - backend_network

  backend:
    build: ./backend
    networks:
      - frontend_network
      - backend_network
    ports:
      - 8080:8080
    env_file:
      - ./backend/api/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    networks:
      - frontend_network
    ports:
      - 3000:3000
    depends_on:
      - backend

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
