version: "3.8"
services:
  backend:
    build: ./backend
    networks:
      - frontend_network
      - backend_network
    ports:
      - 8080:8080

  db:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo-app
    networks:
      - backend_network

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
