import Form from "@/components/Form";
import MainLayout from "@/layouts/MainLayout";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>TODO-APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MainLayout>
        <Form />
      </MainLayout>
    </>
  );
}
